spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/clinic_platform
    username: ${CLINIC_DB_USERNAME:clinic_app}
    password: ${CLINIC_DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations:
      - classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/clinic-platform